- name: Debug
  ansible.builtin.debug:
    msg: "{{ bind_volume }}"

- name: Create Directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ bind_volume.source }}"
