---
# tasks file for tigera-operator

- name: Add Calico Repo
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://projectcalico.docs.tigera.io/charts
  register: repo_add

- name: Update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: default
    state: absent
    update_repo_cache: true

- name: Deploy Calico
  kubernetes.core.helm:
    name: calico
    create_namespace: true
    release_namespace: tigera-operator
    chart_ref: projectcalico/tigera-operator
    chart_version: "v{{ helm_tigera_operator_chart_version }}"
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
